name: CI

on:
 push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@dev
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Override API endpoint.
      run: echo "https://gygb-backend-v1-dev.herokuapp.com/v1/" > .env.production.local
    - name: NPM Install
      run: npm install
    - name: NPM Build
      run: npm run build
    - name: GitHub Action for Firebase
      uses: w9jds/firebase-action@v1.3.0
      with:
          args: deploy --only hosting:dev
      env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
