name: CI

on:
 push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
    - name: Download Artifact
      uses: actions/download-artifact@master
      with:
        name: dist
    - name: GitHub Action for Firebase
      uses: w9jds/firebase-action@v1.3.0
      with:
          args: deploy --only hosting
      env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
