name: CI

on:
 push:
    branches:
      - dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Override API endpoint.
      run: echo "REACT_APP_API_URL=https://gygb-backend-v1-dev.herokuapp.com/v1/" > ${{ GITHUB_WORKSPACE }}/gygb-client-web/.env.production.local
    - name: NPM Install
      run: npm install
    - name: NPM Build
      run: npm run build
    - name: Archive Development Build
      uses: actions/upload-artifact@master
      with:
        name: build-dev
        path: build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build-dev
          path: build/
      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@v1.3.0
        with:
          args: deploy --project development --only hosting:web
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}