name: CI

on:
 push:
    branches:
      - production

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: NPM Install
      run: npm install
    - name: NPM Build
      run: npm run build
    - name: Archive Production Build
      uses: actions/upload-artifact@master
      with:
        name: build-prod
        path: build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build-prod
          path: build/
      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@v1.3.0
        with:
          args: deploy --project production --only hosting:web
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
